#define BP35A1_RX 26
#define BP35A1_TX 0
#define B_ROUTE_ID "<POWER ID>"
#define B_ROUTE_PASSWORD "POWER ID PASSWORD"
#define WIFI_SSID "<SSID>"
#define WIFI_PASSPHRASE "<SSID PASSWORD>"
#define MQTT_SERVER_URL "<MQTT SERVER>"
#define MQTT_SERVER_PORT 1883
#define MQTT_CONNECT_ID "SmartMeter"
#define MQTT_CONNECT_USER ",MQTT ID>"
#define MQTT_CONNECT_USER_PW "<MQTT PASSWORD>"
#define NTP_SERVER "<NTP SERVER>"
#define MAX_POWER 800
#define AVG_POWER 799